# Generated by Django 5.0 on 2023-12-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rabbit_images/'),
        ),
    ]
